// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in "/sbnd/app/users/brindenc/analyze_sbnd/nue/fullsample/./NuEScatter_events.C";

#endif
